[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PyWorktime"
version = "0.1.1"
dependencies = [
    'importlib-metadata; python_version<"3.10"',
]

[project.scripts]
worktimer = "pytimer.ui:main"